run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosec
    - revive
    - unused
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - misspell
    - funlen
    - lll
    - bodyclose
    - whitespace
    - prealloc
    - errorlint
    - nestif
    - nolintlint

linters-settings:
  funlen:
    lines: 60
    statements: 40
  lll:
    line-length: 120
  gocyclo:
    min-complexity: 12
  nestif:
    min-complexity: 4
  goimports:
    local-prefixes: github.com/leosocy/diffah
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
    disabled-tags:
      - experimental

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - lll
        - dupl
